name: meter_sense
description: "Meter Controlling Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_reactive_ble: ^5.1.1
  functional_data: ^1.0.0
  #  format Date Time
  intl: ^0.18.1

  provider: ^6.0.1
  auto_size_text: ^3.0.0

  #  DataBase Storage
  curved_navigation_bar: ^1.0.3
  flutter_custom_clippers: ^2.1.0
  fl_chart: ^0.64.0
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
#  flutter_barcode_scanner: ^2.0.0
  collection: ^1.15.0
  sqflite_sqlcipher: ^2.2.1
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.6
  get_storage: ^2.1.1
  meta: ^1.11.0
  path: ^1.9.0


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
